### ISSUE TITLE
Can not read the dataset.

### ISSUE THREAD

**Issue by protsenkovi** [ClockworkBunny/MHMS_DEEPLEARNING#4]
>>> a = cPickle.load(open("./data/data_seq.p", "rb"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named multiarray

Could you please upload dataset in other format (e.g. csv)?

**Comment by shanchao0906** [comment]
data文件是加密文件，文章里不是说提取的特征是公开的吗

**Comment by protsenkovi** [comment]
> data文件是加密文件，文章里不是说提取的特征是公开的吗

Thank you for your response. I've already managed to unpickle data with proper python environment.
